In [1]:
import torch

In [3]:
x = torch.randn(3, requires_grad = True)
print(x)

tensor([-1.1387e+00,  3.4619e-02, -8.4854e-04], requires_grad=True)


In [4]:
y = x + 2
print(y)

tensor([0.8613, 2.0346, 1.9992], grad_fn=<AddBackward0>)


In [17]:
z = y*y*2
z = z.mean()
print(z)

z.backward()
print(x.grad)

tensor(5.9187, grad_fn=<MeanBackward0>)
tensor([ 2.6412, 13.5641,  5.3391])


In [16]:
# If the values are not scaler, then we need to define a vector and apply the same within the backward function

z = y*y*2
print(z)

v = torch.tensor([0.1, 1.0, 0.001], dtype=torch.float32)
z.backward(v)
print(x.grad)

tensor([1.4836, 8.2793, 7.9932], grad_fn=<MulBackward0>)
tensor([ 1.4929, 10.8513,  2.6735])


In [18]:
# how to prevent from tracking the gradients

x = torch.randn(3, requires_grad = True)
print(x)

# Three techniques as below:
  # x.requires_grad_(False)
  # x.detach()
  # with torch.no_grad()

tensor([-1.8194, -1.4187,  1.2261], requires_grad=True)


In [19]:
x.requires_grad_(False)
print(x)

tensor([-1.8194, -1.4187,  1.2261])


In [20]:
y = x.detach()
print(y)

tensor([-1.8194, -1.4187,  1.2261])


In [22]:
with torch.no_grad():
  y = x + 2
  print(y)

tensor([0.1806, 0.5813, 3.2261])


In [25]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
  model_output = (weights*3).sum()
  model_output.backward()

  print(weights.grad)

  weights.grad.zero_() #empty gradients

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
