In [27]:
import torch
import numpy as np

In [2]:
x = torch.empty(1)
print(x)

tensor([2.6006e-36])


In [3]:
x = torch.empty(3) # 1D vector with 3 elements
print(x)

tensor([2.6006e-36, 0.0000e+00, 5.0447e-44])


In [4]:
x = torch.empty(2, 3) # 2D matrix
print(x)

tensor([[2.6006e-36, 0.0000e+00, 1.5975e-43],
        [1.3873e-43, 1.4574e-43, 6.4460e-44]])


In [5]:
x = torch.empty(2, 2, 3) # 3D
print(x)

tensor([[[2.6006e-36, 0.0000e+00, 1.5975e-43],
         [1.3873e-43, 1.4574e-43, 6.4460e-44]],

        [[1.4153e-43, 1.5274e-43, 1.5695e-43],
         [1.6255e-43, 1.6956e-43, 0.0000e+00]]])


In [6]:
x = torch.rand(2, 2)
print(x)

tensor([[0.2983, 0.3203],
        [0.8213, 0.7177]])


In [8]:
x = torch.zeros(2, 2)
print(x)

tensor([[0., 0.],
        [0., 0.]])


In [10]:
x = torch.ones(2, 2)
print(x)
print(x.dtype)

tensor([[1., 1.],
        [1., 1.]])
torch.float32


In [11]:
x = torch.ones(2, 2, dtype=torch.int)
print(x.dtype)

torch.int32


In [13]:
x = torch.ones(2, 2, dtype=torch.int)
print(x.size())

torch.Size([2, 2])


In [14]:
x = torch.tensor([2.5, 0.1])
print(x)

tensor([2.5000, 0.1000])


In [15]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)

tensor([[0.5574, 0.7087],
        [0.1021, 0.9725]])
tensor([[0.2696, 0.2205],
        [0.7243, 0.8714]])


In [16]:
z = x + y
print(z)

tensor([[0.8270, 0.9292],
        [0.8264, 1.8438]])


In [17]:
z = torch.add(x,y)
print(z)

tensor([[0.8270, 0.9292],
        [0.8264, 1.8438]])


In [18]:
y.add_(x)
print(y)

tensor([[0.8270, 0.9292],
        [0.8264, 1.8438]])


In [19]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
z = torch.sub(x,y)
print(z)

tensor([[ 0.1205, -0.0298],
        [-0.3150,  0.8040]])


In [20]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
z = torch.mul(x,y)
print(z)

tensor([[0.2895, 0.1837],
        [0.9024, 0.0239]])


In [21]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
z = torch.div(x,y)
print(z)

tensor([[0.8698, 4.4885],
        [1.7485, 0.1412]])


In [23]:
x = torch.rand(5, 3) 
print(x[:, 1]) # Slicing

tensor([0.1290, 0.5425, 0.7245, 0.4576, 0.9696])


In [24]:
x = torch.rand(4, 4)
print(x) 

y = x.view(16) # reshape
print(y)

tensor([[0.5645, 0.2796, 0.2133, 0.3319],
        [0.8324, 0.5823, 0.8970, 0.2910],
        [0.1037, 0.3487, 0.4770, 0.1154],
        [0.0758, 0.6904, 0.2034, 0.8563]])
tensor([0.5645, 0.2796, 0.2133, 0.3319, 0.8324, 0.5823, 0.8970, 0.2910, 0.1037,
        0.3487, 0.4770, 0.1154, 0.0758, 0.6904, 0.2034, 0.8563])


In [26]:
x = torch.rand(4, 4)
print(x) 

y = x.view(-1, 8) # reshape
print(y)
print(y.size())

tensor([[0.8820, 0.5985, 0.1961, 0.8055],
        [0.9335, 0.4186, 0.6492, 0.9000],
        [0.8343, 0.6362, 0.3737, 0.1061],
        [0.5722, 0.5100, 0.1659, 0.2763]])
tensor([[0.8820, 0.5985, 0.1961, 0.8055, 0.9335, 0.4186, 0.6492, 0.9000],
        [0.8343, 0.6362, 0.3737, 0.1061, 0.5722, 0.5100, 0.1659, 0.2763]])
torch.Size([2, 8])


In [32]:
a = torch.ones(5)
print(a)
print(type(a))

b = a.numpy()
print(b)
print(type(b))

tensor([1., 1., 1., 1., 1.])
<class 'torch.Tensor'>
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [33]:
a = torch.ones(5)
b = a.numpy()

a.add_(1)
print(a) # since they share the same memory, anything changed in a will have impact on b

print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [34]:
a = np.ones(5)
print(a)

b = torch.from_numpy(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [37]:
if torch.cuda.is_available():
  device = torch.device("cuda")
  x = torch.ones(5, device=device)
  y = torch.ones(5)
  y = y.to(device)
  print(x)
  print(y)
else:
  print("cpu")

cpu


In [38]:
x = torch.ones(5, requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
