In [1]:
import torch

In [2]:
x = torch.empty(1)
print(x)

tensor([2.6006e-36])


In [3]:
x = torch.empty(3) # 1D vector with 3 elements
print(x)

tensor([2.6006e-36, 0.0000e+00, 5.0447e-44])


In [4]:
x = torch.empty(2, 3) # 2D matrix
print(x)

tensor([[2.6006e-36, 0.0000e+00, 1.5975e-43],
        [1.3873e-43, 1.4574e-43, 6.4460e-44]])


In [5]:
x = torch.empty(2, 2, 3) # 3D
print(x)

tensor([[[2.6006e-36, 0.0000e+00, 1.5975e-43],
         [1.3873e-43, 1.4574e-43, 6.4460e-44]],

        [[1.4153e-43, 1.5274e-43, 1.5695e-43],
         [1.6255e-43, 1.6956e-43, 0.0000e+00]]])


In [6]:
x = torch.rand(2, 2)
print(x)

tensor([[0.2983, 0.3203],
        [0.8213, 0.7177]])


In [8]:
x = torch.zeros(2, 2)
print(x)

tensor([[0., 0.],
        [0., 0.]])


In [10]:
x = torch.ones(2, 2)
print(x)
print(x.dtype)

tensor([[1., 1.],
        [1., 1.]])
torch.float32


In [11]:
x = torch.ones(2, 2, dtype=torch.int)
print(x.dtype)

torch.int32


In [13]:
x = torch.ones(2, 2, dtype=torch.int)
print(x.size())

torch.Size([2, 2])


In [14]:
x = torch.tensor([2.5, 0.1])
print(x)

tensor([2.5000, 0.1000])


In [15]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)

tensor([[0.5574, 0.7087],
        [0.1021, 0.9725]])
tensor([[0.2696, 0.2205],
        [0.7243, 0.8714]])


In [16]:
z = x + y
print(z)

tensor([[0.8270, 0.9292],
        [0.8264, 1.8438]])


In [17]:
z = torch.add(x,y)
print(z)

tensor([[0.8270, 0.9292],
        [0.8264, 1.8438]])


In [18]:
y.add_(x)
print(y)

tensor([[0.8270, 0.9292],
        [0.8264, 1.8438]])
